<h3>Add new busline</h3>


<?php 
if(sizeof($this->errors) != 0){
    foreach($this->errors as $error){
        echo($error . "<br />");  
    }
}?>
<?php if(isset($this->message)){ echo($this->message);}?>
<table style="width: 300px;">

<form action="/uus/busstop/add" method="post">

<tr>
    <td><label for="busstopName">Busstop name:</label></td>
    <td><input type="text" name="busstopName" value="" /></td>
</tr>
<tr>
<td><label for="xCoord">X coord (e.g 45): </label></td>
<td><input type="text" name="xCoord" /></td>
</tr>
<tr>
    <td><label for="yCoord">Y coord (e.g 45): </label></td>
    <td><input type="text" name="yCoord" /></td>
</tr>
<tr>
    <td></td>
    <td><input type="submit" value="Submit" /></td>
</tr>

</form>


</table>