<!doctype>
<html>
<head>
	<title>Busline application</title>
</head>

<body>
	<div id="header">
        <?php echo $this->render("header.phtml");?>
    </div>
    <div id="nav">
        <?php echo $this->render("menu.phtml");?>
    </div>
	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>
    <div id="footer">
        <?php echo $this->render("footer.phtml");?>
    </div>
    
</body>
</html>