<!doctype>
<html>
<head>
<?php $this->headlink()->appendStylesheet($this->baseUrl('public/css/stylesheet.css') , ''); ?>
<?php echo $this->headlink();?>
<?php echo $this->headScript();?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(function() {
    $('.log').ajaxStart(function() {
        $(this).text('Sooritatakse ajax päringut');
    });
    

    $('#buslines').hide();
    $('#busstops').hide();
    
    
    $('a.busline').click(function() { 
        $('#buslines').html("");
        $('#buslines').toggle();
        if($('#buslines').is(':visible')){
            getList('busline');
        }    
    });
    
    $('a.busstop').click(function() { 
        $('#busstops').html("");
        $('#busstops').toggle();
        if($('#busstops').is(':visible')){
            getList('busstop');
        }    
    });
    
});
</script>
<title>Busline application</title>
</head>
<body>
    <?php $this->render('breadcrumbs.phtml');?>
    <div id="header">
        <?php echo $this->render("header.phtml");?>
    </div>
    <div id="nav">
        <?php echo $this->render("menu.phtml");?>
    </div>
    <div id="breadcrumbs">You are at: <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();?></div>
	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>
    <div id="footer">
        <?php echo $this->render("footer.phtml");?>
    </div>
</body>
</html>