<h3>Edit: "<?php echo $this->buslineName;?>" busline</h3>
<?php 
if(sizeof($this->errors) != 0){
    foreach($this->errors as $error){
        echo($error . "<br />");  
    }
}?>
<table style="width: 200px;">
<form action="<?php echo($this->baseUrl()."/busline/edit");?>" method="post">
<input type="hidden" name="formBuslineId" value="<?php echo $this->buslineId;?>" />
<tr>
    <td><label for="buslineName">Buslinename:</label></td>
    <td><input type="text" name="buslineName" value="<?php echo $this->buslineName;?>" /></td>
</tr>
<tr>
    <td style="vertical-align: top;"><label for="buslineDescription">Description:</label></td>
    <td><textarea rows="5" cols="50" name="buslineDescription"><?php echo $this->buslineDescription; ?></textarea></td>
</tr>
<tr>
    <td style="vertical-align: top;">Select busstops:</td>
    <td><select name="busstopList[]" size="5" multiple="multiple">
    <?php foreach($this->busstops as $busstop){?>
        <option value="<?php echo($busstop->id);?>" <?php if(in_array($busstop->id, $this->selected)) echo('selected = "seleced"');?>><?php echo($busstop->name) ;?></option>
    <?php };?>
    </select></td>

</tr>
<tr>
    <td></td>
    <td><input type="submit" value="Submit" /></td>
</tr>

</form>
</table>