<h3>Edit: <?php echo $this->buslineName;?></h3>
<table style="width: 200px;">


<form action="/uus/busline/edit" method="post">
<input type="hidden" name="formBuslineId" value="<?php echo $this->buslineId;?>" />
<tr>
    <td><label for="buslineName">Buslinename:</label></td>
    <td><input type="text" name="buslineName" value="<?php echo $this->buslineName;?>" /></td>
</tr>
<tr>
    <td style="vertical-align: top;"><label for="buslineDescription">Description:</label></td>
    <td><textarea rows="5" cols="50" name="buslineDescription"><?php echo $this->buslineDescription; ?></textarea></td>
</tr>
<tr>
    <td></td>
    <td><input type="submit" value="Submit" /></td>
</tr>

</form>


</table>