
<h3><?php echo $this->name;?> <a href="<?php echo $this->url(array('controller'=>'busline','action'=>'edit', 'id' => $this->id));?>"><img src="<?php echo $this->baseUrl()."/public/img/application_edit.png";?>" /></a></h3>
<p><?php echo $this->description;?></p>
<p><small>Date added: <?php echo date("d-m-Y", strtotime($this->dateAdded));?></small></p>
<table style="width: 400px;">
    <th><?php 
    
    if(sizeof($this->busstops) != 0){
        echo("Busstops associated with this busline (".$this->name."):"); 
    } else {
        echo("No busstops associated");
    }?></th>
    <?php foreach($this->busstops as $busstop): ?>
    <tr>
        <td><a href="<?php echo $this->url(array('controller'=>'busstop','action'=>'view', 'id' => $busstop->id));?>"><?php echo($busstop->name);?></a></td>
    </tr>
    <?php endforeach;?>
</table>
